### ISSUE TITLE
Global strict decryption mode

### ISSUE THREAD

**Issue by franky47** [47ng/prisma-field-encryption#8]
Adding a global strict decryption mode that throws errors when decryption fails (missing key) should help avoid building layers of encryption in migrations.

Use-case:
1. The decryption key is missing, encrypted data is returned in ciphertext (A)
2. The data migration re-encrypts ciphertext A with encryption key, producing ciphertext B
3. Decryption of re-encrypted records yield ciphertext A

**Comment by franky47** [comment]
The encryption key is automatically added to the list of decryption keys, so you should not need to add it yourself (this list is only for key rotation). Are you sure your environment variables are correctly loaded at the time when the middleware is initialised?

**Comment by aortukgp** [comment]
Thank you for your answer! I have removed the key `PRISMA_FIELD_DECRYPTION_KEYS` from the `.env` file. Yes I am sure that the environment  file is loaded when the middleware is initialized, because if I comment out the key `PRISMA_FIELD_ENCRYPTION_KEY` I get the following error:

`Error: [prisma-field-encryption] Error: no encryption key provided.`

I can explain how the file is structured. It is a javascript file with several APIs.

At the beginning of the file I write the following code.

```
const {
    PrismaClient
} = require("@prisma/client")

const { 
    fieldEncryptionMiddleware
} = require('prisma-field-encryption')

const prisma = new PrismaClient()

prisma.$use(
    fieldEncryptionMiddleware()
)
```
Then follow 2 APIs

**First**
```
router.post('/create', [passport.authenticate('jwt', {session: false}), middleware.session.isValid], async (req, res) => {

    const {
        name,
        surname,
        CF
    } = req.body.patient

    patient = await prisma.patients.create({
        data: {
            name,
            surname,
            CF
        }
    })

    return res.status(200).json({
        msg: `Patient created`,
        patient
    })

})
```
**Second**
```
router.get('/read/detail/:CF', [passport.authenticate('jwt', {session: false}), middleware.session.isValid], async (req, res) => {

    const {
        CF
    } = req.params

    const patient = await prisma.patients.findUnique({
        where: {
            CF
        },
        include: {
            patients_pathologies: {
                include: {
                    therapy: true
                }
            }
        }
    })

    if(!patient) return res.status(404).json({
        msg: `Patient '${CF}' not found`
    })

    return res.status(200).json(patient)

})
```

Unfortunately in the second API I get the patient's name and surname encrypted **:(**

I also share the file `.prisma` for you

```
model patients {

  id Int @id @default(autoincrement())

  CF         String    @unique
  name       String    @db.VarChar(50) /// @encrypted
  surname    String    @db.VarChar(50) /// @encrypted
  email      String?   @db.VarChar(50)
  phone      String?   @db.VarChar(50)
  date_birth DateTime?

  patients_pathologies patients_pathologies[]

}
```

**Comment by aortukgp** [comment]
Yes, i show you directly:

**Client**
![image](https://user-images.githubusercontent.com/91208291/177337733-3f3a9fc2-f12e-4bae-93f1-b7afcf65f457.png)

----

**Database**
![image](https://user-images.githubusercontent.com/91208291/177337000-ef733b87-844a-47a3-a111-033ba805a7ac.png)

In the two input fields there are uppercase()

_(Sorry if I'm asking for help with this issue)_

**Comment by franky47** [comment]
The ciphertext is surprisingly short, do you know if the underlying clear-text data was short too (only a few characters long I'd wager) ? This rules out double-encryption anyway.

If you import your encryption key [here](https://cloak.47ng.com/), does it show the same fingerprint (8 hex characters next to "Use for encryption"), ie `d9ca6d57` ? If not, it means the data has been encrypted using a different key.

**Comment by franky47** [comment]
Ok, let's see if we can get some errors showing: could you do the following change please? 
```diff
model patients {
  ...
- name       String    @db.VarChar(50) /// @encrypted
+ name       String    @db.VarChar(50) /// @encrypted?strict
- surname    String    @db.VarChar(50) /// @encrypted
+ surname    String    @db.VarChar(50) /// @encrypted?strict
  ...
}
```
With `strict` mode enabled, decryption errors will throw rather than pass the ciphertext through. Maybe it will shed more light as to what went wrong, although it should already show errors in the console (admittedly using the string "encryption error", I just noticed a copy/pasta typo there, it should be "decryption error").

**Comment by franky47** [comment]
I've released `1.4.0-beta.3`, which includes debugging printouts. You can set the `DEBUG` environment variable to `prisma-field-encryption:*` to print everything, hopefully that will tell you more about what's going on.

**Comment by aortukgp** [comment]
> Ok, let's see if we can get some errors showing: could you do the following change please?
> 
> ```diff
> model patients {
>   ...
> - name       String    @db.VarChar(50) /// @encrypted
> + name       String    @db.VarChar(50) /// @encrypted?strict
> - surname    String    @db.VarChar(50) /// @encrypted
> + surname    String    @db.VarChar(50) /// @encrypted?strict
>   
> }
> ```
> 
> With `strict` mode enabled, decryption errors will throw rather than pass....


**Hi franky**, thanks for your availability!

The module does not print errors in the console and does not create log files.

I have tried to comment out the line of code (in my module it was in line **78**) and I have also edited the schema.prisma file doing this job:

```
model patients {

  id Int @id @default(autoincrement())

  CF         String    @unique
  name       String    @db.VarChar(50) /// @encrypted?strict
  surname    String    @db.VarChar(50) /// @encrypted?strict
  ..

  patients_pathologies patients_pathologies[]

}
```

But the data is still not decrypted :(

I can tell you that the text in the patients.ts file has changed:

```
/**
 * Internal model:
 * {
 *   "cursor": "id",
 *   "fields": {
 *     "name": {
 *       "encrypt": true,
 *       "strictDecryption": true <-- changed
 *     },
 *     "surname": {
 *       "encrypt": true,
 *       "strictDecryption": true <-- changed
 *     }
 *   },
 *   "connections": {
 *     "user": {
 *       "modelName": "users",
 *       "isList": false
 *     },
 *     "patients_pathologies": {
 *       "modelName": "patients_pathologies",
 *       "isList": true
 *     }
 *   }
 * }
 */
```
_I add: Every time I make a change I run both commands_

```
npx prisma migrate dev --name fix
npx prisma generated
```

_Then I delete the data from the database and recreate it._

**Comment by franky47** [comment]
Ahhh search no longer, I found the issue..

I use a regexp to try and detect a ciphertext in the @47ng/cloak format, and it was wrong somehow to assume the ciphertext part of the string was 22 characters long at least (yours is 11).

I'll run some more tests on this with various short clear-text lengths, fix the regexp and release a fix for you to try, sorry about that!

**Comment by franky47** [comment]
Now my tests in `@47ng/cloak` seem to be correct on ciphertext minimum length (an empty string encrypts into a 63-character encrypted string), which brings me to the obvious thing I did not notice in your Prisma schema: the maximum length of 50 characters for your encrypted fields.

What happened is that the ciphertext was truncated, passing under the threshold of the regexp detection, and passed through as-is.

Since ciphertext is quite a bit larger than clear-text, I'd suggest raising this limit (for reference, a 50-character clear-text input encrypts into a 127-characters long encrypted string, so better set it to 130 for safety), and enforcing the actual 50 character length limit in your API before passing it to Prisma.

Sorry I got you into a wild goose chase, when the answer was actually right in your second message. 😅

**Comment by aortukgp** [comment]
waah, now it's working properly!! 😂😂😂
damn length! 😂😂😂
i am very happy now, because your package is very comfortable!!

The data I would like to encrypt is longer, the name and surname were a test. The important thing is that we managed to reach the goal! You are very good, thank you very much Franky!

**Comment by Serdans** [comment]
I seem to be experiencing this issue where my data is encrypted in the database, but it is returned without decrypting. I'm using MongoDB and assume the character length is not the cause of this?

Using `///@encrypted?mode=strict` is not throwing an error.

**Comment by franky47** [comment]
@serdans could you check that you get the **same** ciphertext from Prisma that the one stored in the database? Just want to rule out a double encryption case.

**Comment by Serdans** [comment]
Yup it's the same ciphertext.

**Comment by franky47** [comment]
If you turn on [debugging](https://github.com/47ng/prisma-field-encryption#debugging), does it reveal anything useful? Mind that some values may be printed in clear text there.

**Comment by Serdans** [comment]
I'm using NextJS and setting the `DEBUG` value in my `next.config.js` gives me the following error when running it:

```
Server Error
Error: Invalid left-hand side in assignment

This error happened while generating the page. Any console logs will be displayed in the terminal window.

 at __webpack_require__ (/home/andres/Documents/development/web/subpanel_v3/.next/server/webpack-runtime.js:33:43)
    at eval (webpack-internal:///(rsc)/./node_modules/.pnpm/prisma-field-encryption@1.5.0_@prisma+client@5.5.2/node_modules/prisma-field-encryption/dist/index.js:6:19)
    at (rsc)/./node_modules/.pnpm/prisma-field-encryption@1.5.0_@prisma+client@5.5.2/node_modules/prisma-field-encryption/dist/index.js (/home/andres/Documents/development/web/subpanel_v3/.next/server/vendor-chunks/prisma-field-encryption@1.5.0_@prisma+client@5.5.2.js:80:1)
```

**Comment by franky47** [comment]
Looks like an import error, anyway you probably don't need to set it in the Next.js config, a `DEBUG="prisma-field-encryption:*" next dev` should work.

**Comment by Serdans** [comment]
I see it's successfully decrypting it if I'm selecting the data directly, e.g. `prisma.user.findFirst`, but doing a 
```
prisma.order.findMany({
  include: {
     user: {
       select: {
          myDecryptedField: true
       } 
    }
  }
```

does not decrypt the field.
